shell.execute("delete", "farm.lua")
shell.execute("wget", "https://raw.githubusercontent.com/MayaSapphire/turtle-control-suite/refs/heads/main/farming/farm.lua")
shell.execute("delete", "startup.lua")
shell.execute("wget", "https://raw.githubusercontent.com/MayaSapphire/turtle-control-suite/refs/heads/main/farming/startup.lua")
shell.execute("delete", "update.lua")
shell.execute("wget", "https://raw.githubusercontent.com/MayaSapphire/turtle-control-suite/refs/heads/main/farming/update.lua")